$mainMod = SUPER
$scriptsDir = $HOME/.config/hypr/scripts

$Touchpad_Device=asuf1204:00-2808:0202-touchpad


bind = , xf86TouchpadToggle, exec, $scriptsDir/TouchPad.sh # disable touchpad

$TOUCHPAD_ENABLED = true
device {
  name = $Touchpad_Device
  enabled = $TOUCHPAD_ENABLED
}

# Fix lid switch resolutions to match hardware (1366x768@60)
bindl = , switch:off:Lid Switch,exec,hyprctl keyword monitor "eDP-1, 1366x768@60, auto, 1"
bindl = , switch:on:Lid Switch,exec,hyprctl keyword monitor "eDP-1, disable"

# Universal fallback
monitor = eDP-1, preferred, auto, 1
