// Generated by ScreenMode.sh — edit the PROFILES table, not this file.
// profile: dark — 2700K chromaticity, peak white preserved.
precision highp float;
varying vec2 v_texcoord;
uniform sampler2D tex;

// sRGB <-> linear. Clamped before pow() so a stray negative cannot produce NaN.
vec3 toLinear(vec3 c) {
    c = clamp(c, 0.0, 1.0);
    return mix(c / 12.92, pow((c + 0.055) / 1.055, vec3(2.4)), step(vec3(0.04045), c));
}
vec3 toSRGB(vec3 c) {
    c = clamp(c, 0.0, 1.0);
    return mix(c * 12.92, 1.055 * pow(c, vec3(1.0 / 2.4)) - 0.055, step(vec3(0.0031308), c));
}
void main() {
    vec4 pixColor = texture2D(tex, v_texcoord);
    vec3 lin = toLinear(pixColor.rgb) * vec3(1.000000,0.656093,0.349563);
    gl_FragColor = vec4(toSRGB(lin), pixColor.a);
}
