// Generated by ScreenMode.sh — edit the PROFILES table, not this file.
// profile: vivid — saturation in linear light, contrast as an S-curve in gamma space.
precision highp float;
varying vec2 v_texcoord;
uniform sampler2D tex;

const float SATURATION = 1.14;
const float CONTRAST   = 1.07;

// sRGB <-> linear. Clamped before pow() so a stray negative cannot produce NaN.
vec3 toLinear(vec3 c) {
    c = clamp(c, 0.0, 1.0);
    return mix(c / 12.92, pow((c + 0.055) / 1.055, vec3(2.4)), step(vec3(0.04045), c));
}
vec3 toSRGB(vec3 c) {
    c = clamp(c, 0.0, 1.0);
    return mix(c * 12.92, 1.055 * pow(c, vec3(1.0 / 2.4)) - 0.055, step(vec3(0.0031308), c));
}
void main() {
    vec4 pixColor = texture2D(tex, v_texcoord);

    // Saturate around Rec.709 luma, in linear light so hues do not skew.
    vec3 lin  = toLinear(pixColor.rgb);
    float luma = dot(lin, vec3(0.2126, 0.7152, 0.0722));
    lin = mix(vec3(luma), lin, SATURATION);

    // Contrast around mid-grey, in gamma space where 0.5 is perceptual middle.
    vec3 enc = toSRGB(lin);
    enc = clamp((enc - 0.5) * CONTRAST + 0.5, 0.0, 1.0);

    gl_FragColor = vec4(enc, pixColor.a);
}
