[zen|*proxmox*]
tab = tab
backslash = backslash
capslock = capslock
enter = enter
space = space
leftshift = leftshift
rightshift = rightshift
esc = esc
leftalt = leftalt
rightalt = rightalt

[zen|*novnc*]
tab = tab
backslash = backslash
capslock = capslock
enter = enter
space = space
leftshift = leftshift
rightshift = rightshift
esc = esc
leftalt = leftalt
rightalt = rightalt

[lutris]
tab = tab
backslash = backslash
capslock = capslock
enter = enter
space = space
leftshift = leftshift
rightshift = rightshift
esc = esc
leftalt = leftalt
rightalt = rightalt

[wine]
tab = tab
backslash = backslash
capslock = capslock
enter = enter
space = space
leftshift = leftshift
rightshift = rightshift
esc = esc
leftalt = leftalt
rightalt = rightalt

[*-exe]
tab = tab
backslash = backslash
capslock = capslock
enter = enter
space = space
leftshift = leftshift
rightshift = rightshift
esc = esc
leftalt = leftalt
rightalt = rightalt
