# /* ---- 💫 Hypridle — NixOS compatible ---- */

general {
    lock_cmd            = pidof hyprlock || hyprlock
    unlock_cmd          = killall -q hyprlock
    before_sleep_cmd    = loginctl lock-session
    after_sleep_cmd     = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

# Turn off screen faster when already locked
listener {
    timeout    = 30
    on-timeout = pidof hyprlock && hyprctl dispatch dpms off
    on-resume  = pidof hyprlock && hyprctl dispatch dpms on
}

# Lock after 3 min of idle
listener {
    timeout    = 180
    on-timeout = loginctl lock-session
}

# Turn screen off after 5 min of idle
listener {
    timeout    = 300
    on-timeout = hyprctl dispatch dpms off
    on-resume  = hyprctl dispatch dpms on
}
